# Generated by Django 5.2.8 on 2025-11-24 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anggota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_anggota', models.CharField(max_length=10, unique=True)),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('judul', models.CharField(max_length=200)),
                ('penulis', models.CharField(max_length=100)),
                ('tahun_terbit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pinjam', models.DateTimeField(auto_now_add=True)),
                ('tanggal_kembali', models.DateField(blank=True, null=True)),
                ('anggota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.anggota')),
                ('buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.buku')),
            ],
        ),
    ]
