# Generated by Django 5.2.1 on 2025-11-24 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peminjaman',
            name='tanggal_kembali',
        ),
        migrations.RemoveField(
            model_name='peminjaman',
            name='tanggal_pinjam',
        ),
        migrations.AlterField(
            model_name='peminjaman',
            name='anggota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_pinjam', to='data.anggota'),
        ),
        migrations.AlterField(
            model_name='peminjaman',
            name='buku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_pinjam', to='data.buku'),
        ),
    ]
