# Generated by Django 5.2.1 on 2025-11-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_remove_peminjaman_tanggal_kembali_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peminjaman',
            name='tanggal_kembali',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peminjaman',
            name='tanggal_pinjam',
            field=models.DateField(default='2023-01-01'),
            preserve_default=False,
        ),
    ]
