# Generated by Django 5.2.8 on 2026-01-19 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_peminjaman_tanggal_kembali_peminjaman_tanggal_pinjam'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='jumlah_stok',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='peminjaman',
            name='tanggal_pinjam',
            field=models.DateField(auto_now_add=True),
        ),
    ]
